site_name: DOSAR Outreach Materials
site_url: https://opensciencegrid.github.io/dosar
repo_url: https://github.com/opensciencegrid/dosar
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- Materials:
  - 'Polar Hackathon Schedule': 'Materials/DT2017.md'
  - 'Polar Hackathon Materials': 'Materials/TriesteMaterials.md'


markdown_extensions:
  - admonition
  - osg_markdown.colors
