site_name: DOSAR Outreach Materials
site_url: https://opensciencegrid.github.io/dosar
repo_url: https://github.com/opensciencegrid/dosar
theme: readthedocs

pages:
- Home: 'index.md'
- Materials:
  - 'Data Sao Paulo Schedule': 'Materials/DT2017.md'
  - 'Data Sao Paulo Materials': 'Materials/Materials.md' 
  - 'Polar Hackathon Schedule': 'Materials/DT2017.md'
  - 'Polar Hackathon Materials': 'Materials/Materials.md'


markdown_extensions:
  - admonition
  - osg_markdown.colors
